theme: jekyll-theme-minimal
title: Welcome! Thanks for stopping by.
image: [headshot]
description: My name is Madison and I am a rising third year graduate student in the Department of Psychology at the University of California, Davis. 
