theme: jekyll-theme-minimal
title: Welcome!

![Headshot of Madison Barker](https://user-images.githubusercontent.com/59705627/125537974-f062a999-8230-4fd2-9a33-a5267305959a.png "Madison Barker")

description: My name is Madison and I am a rising third year graduate student in the Department of Psychology at the University of California, Davis. 
