theme: jekyll-theme-minimal
layout: single
title: Welcome!
description: My name is Madison and I am a rising third year graduate student in the Department of Psychology at the University of California, Davis. 
